# Generated by Django 6.1.1 on 2026-09-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='Список вариантов, например: ["Стрижка", "Бритьё", "Окрашивание",]. Пусто = текстовый ввод.', verbose_name='Варианты ответа'),
        ),
    ]
