# Generated by Django 6.1.1 on 2026-09-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='about_text',
            field=models.TextField(blank=True, default='Информация о студии скоро появится.', help_text='Текст, который показывается по кнопке «О нас».', verbose_name='О нас'),
        ),
        migrations.AddField(
            model_name='business',
            name='contacts_text',
            field=models.TextField(blank=True, default='Телефон: ...\nАдрес: ...\nTelegram: @...', help_text='Текст, который показывается по кнопке «Контакты».', verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='Список вариантов, например: ["Стрижка", "Бритьё", "Окрашивание"]. Пусто = текстовый ввод.', verbose_name='Варианты ответа'),
        ),
    ]
