# Generated by Django 6.1.1 on 2026-09-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_business_about_text_business_contacts_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='thank_you_text',
            field=models.TextField(blank=True, default='✅ Спасибо! Ваша заявка принята. Мы свяжемся с вами в ближайшее время.', help_text='Что бот говорит клиенту после завершения опроса.', verbose_name='Сообщение после заявки'),
        ),
    ]
